sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: NvxVJsmJXSt57yppIGUv2C9q3g4tMyLAqCpq4kPcR/Eml2rAGRYI7vZ9/AJ44AK/OFyD3pQ4HCri+ESD7mg2FN22abatpZ2F5Fr5fwCQVREtx24XxEE6F1Vjkd0zVnU22mkwPqrnnuIfpGp+kEZgmiHD2+AQBHjcqd6Zfi1/GSlNo1JrEUi9+fj8j4CNsQ4Ynk2/5uacul1tHnvTOWV5vwh/zhB056vFusG8Tzh/lxbsbhgYYJ9Ij7/7BDXN62cSSnCPXQwWIr1xO9Ohs68RjKLGmAToALQnbR55xjzHat/29tsvS16+WWmfdUGcm6q5baddXcEXB6fGIJ+v2FzXJDsz2MKFdhsTF4hga16xXXKalnBYT8QXjhnqsEIrHqyal5mE56duZHPJWMMLyVoTbrnnEDBMAC+wkZEqTpvvGHNp8NnuN7wws1jqEf7EgDD3Te7pfQ9wpKmmLgJQBS9g8NCjDkzbDrG9rYN0sTnBrYtvYOz/w/wGhhTlzI5j/2KyazuvTcEww2laN8C12dZbaQGjYZKJfU6jFsIPbGbU444Fj+wwKBT0w8PLEGGQhkuwFrNHBiaCmseJq4KZD2LjS4WUnOdC8qi7FLTurjMt4LnN29a0ZxqgrvfY2UwM8LKVA3uZR/5z1cF38/h9fOuECLHmSB/XxI/40j/wJgOybv8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Dr.-Breen-s-Practice_3364
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy